[versions]
agp = "8.13.1"
kotlin = "2.1.21"
composeCompilerGradlePlugin = "2.1.21"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
moshi = "1.15.1"
moshiRetrofit = "2.9.0"
koin = "3.5.0"
junit = "4.13.2"
kotest = "5.8.0"
mockk = "1.13.7"
okhttp = "4.12.0"
coroutines = "1.8.1"
retrofit = "2.9.0"
navigation = "2.9.6"
coil = "2.5.0"
serializable = "1.5.1"
mediaplayer = "1.8.0"

[libraries]
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "composeCompilerGradlePlugin" }
gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
json-moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
json-moshi-retrofit = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "moshiRetrofit" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
serializable = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializable" }
media-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "mediaplayer" }
media-session = { group = "androidx.media3", name = "media3-session", version.ref = "mediaplayer" }

test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
test-kotest = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
test-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
test-koin = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
test-mock-webserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }


